# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: April Mintac Pineda
email: aprilmintacpineda@gmail.com
description: Official portfolio site owned by a software developer named April Mintac Pineda.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aprilmintacpineda.github.io" # the base hostname & protocol for your site
twitter_username: aprmintacpineda
github_username:  aprilmintacpineda
linkedin_username: aprilmintacpineda
sass:
  sass_dir: _sass
  style: compressed

# TODO: add jekyll plugin autoprefixer
# follow up on https://github.com/jekyll/jekyll/issues/6674

# Build settings
markdown: kramdown
